@localhostPort = 7335

GET https://localhost:{{localhostPort}}/movie

###
POST https://localhost:{{localhostPort}}/movie
Content-Type: application/json

{
  "title": "Free Willy",
  "genre": "Family",
  "releaseDate": "1993-07-16",
  "reviewScore": 4.0,
  "boardRating": "PG"
}

###
GET https://localhost:{{localhostPort}}/movie/11
